# Use official JDK image as base
FROM openjdk:17-jdk-slim

# Set work directory
WORKDIR /app

# Copy the JAR file
COPY build/libs/SchoolSystem-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot app uses
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]